### ISSUE TITLE
Amazing material unfortunately I cannot read Bulgarian please point me to youtube video for ASP.NET-MVC-Template/ASP.NET Core/

### ISSUE THREAD

**Issue by khawaja74** [NikolayIT/ASP.NET-Core-Template#50]
Hi NikolayIT, I like your .NET CORE 2.2 template. I dont understand Bulgarian but your youtube videos are helpful as I can understand the code at least. please give me youtube video link for .NET Core 2.2 template.

Many Regards,
Khawaja

**Comment by NikolayIT** [comment]
Hello! I am glad to hear that you like my videos even if you don't understand the language.

There isn't a single video explaining only the ASP.NET Core template code but I can give you 2 videos from November 2018 which are going through the creation of a similar project structure:

* Part 1: https://www.youtube.com/watch?v=Uyv5pqWxF50&feature=youtu.be
* Part 2: https://www.youtube.com/watch?v=WfL6pU_T9ys&feature=youtu.be

Greetings!

**Comment by khawaja74** [comment]
Thank you for the links.

Is there any Final Project on GitHub thats using this .Net Core template. Its Like settings controller but with a little more CRUD operations. It will give a lot of pointers how to best use this .Net Core template and some more usage of services and veiwmodels. Even if there are code comments that can help use this template would be great.

Regards
Khawaja.

Sent from my iPhone

On Aug 17, 2019, at 1:30 AM, Nikolay Kostov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello! I am glad to hear that you like my videos even if you don't understand the language.

There isn't a single video explaining only the ASP.NET<http://ASP.NET> Core template code but I can give you 2 videos from November 2018 which are going through the creation of a similar project structure:

  *   Part 1: https://www.youtube.com/watch?v=Uyv5pqWxF50&feature=youtu.be
  *   Part 2: https://www.youtube.com/watch?v=WfL6pU_T9ys&feature=youtu.be

Greetings!

**Comment by khawaja74** [comment]
Hi Nikolaay, great videos ... I now know dotchka is dot and tikka is Ok in Bulgarian.

I have a suggestion about you breaking mvc core template down to many many projects. Please rethink this approach for the CORE template...

I have no doubt in your approach to break down solutions and separation of concerns but after 20 years I have learnt Keep it simple principle specially from maintenance prospective.

Instead of breaking down solution into projects please work with folders within Funapp.Web. It will speedup you already hyper sonic speed. Least red squiggly lines during cooding and just CTRL . Enter.

Regards
Khawaja

Sent from my iPad

On Aug 17, 2019, at 1:30 AM, Nikolay Kostov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello! I am glad to hear that you like my videos even if you don't understand the language.

There isn't a single video explaining only the ASP.NET<http://ASP.NET> Core template code but I can give you 2 videos from November 2018 which are going through the creation of a similar project structure:

  *   Part 1: https://www.youtube.com/watch?v=Uyv5pqWxF50&feature=youtu.be
  *   Part 2: https://www.youtube.com/watch?v=WfL6pU_T9ys&feature=youtu.be

Greetings!

**Comment by NikolayIT** [comment]
Thank you for your suggestions! Yeah "tochka" means "dot" and "taka" means "so" or "ok". :)

About an example project using this approach, you can see this "news site" here: https://github.com/NikolayIT/PressCenters.com

Greetings!

**Comment by khawaja74** [comment]
Hi NicolayIT,
I am having trouble scaffolding viewmodels added in the solution, have you tried scaffolding any views using the view models? Any help from presscenter.com or original template, I will walk the code on that view model.
Regards,
Khawaja

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by khawaja74** [comment]
Hi Nickolay,

Both of these commands have to run in Package Manager console using the tests project for tests to get going in CI/CD scenario in Azure. And in your build pipeline update this

npm install -g selenium-standalone@latest
selenium-standalone install

**\$(BuildConfiguration)\*tests*.dll!
**\obj\**

This will run the tests in CI/CD scenarios. Thanks for sharing the knowledge some times I miss not knowing Bulgarian, I really want to understand what you are saying but it also keeps me digging your template.

Regards,
Khawaja

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by khawaja74** [comment]
Hi Nikolay,

In your YouTube videos you have power points in English, is that shared some where I really want to read these as I can then understand some of your teachings by watching your videos and reading the power points.

[cid:image003.png@01D56F3D.FDAD9F40]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by NikolayIT** [comment]
Yes, you can download them from: https://www.dropbox.com/s/sgsydzcpmb60tt9/ASP-NET-Core-Jul-2019.zip?dl=0

**Comment by khawaja74** [comment]
Thank you sooo much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NikolayIT** [comment]
You're welcome.

**Comment by khawaja74** [comment]
Hi Nikolay,
Hope you are doing well, thanks again for sharing the ppt files, I am sure you are aware of PWA(progressive-web-app) and it would be really good addition to your already amazing template.
Even making Presscenters.com as an installable app n the mobile devices. All it Needs is following in the template

  1.  dotnet add package WebEssentials.AspNetCore.PWA
  2.  two icons in /img folder "sizes": "192x192" "sizes": "512x512"
  3.  manifest.json in wwwroot
  4.  Add to the ConfigureServices(IServiceCollection services)
  5.  {
  6.        services.AddProgressiveWebApp();
  7.  }
details are here:
https://www.c-sharpcorner.com/article/progressive-web-app-pwa-in-asp-net-core/

Here is the manifest.json I used in the template


{

  "name": "Template",

  "short_name": "T",

  "description": "PWA",

  "icons": [

    {

      "src": "/img/logo192.png",

      "type": "image/png",

      "sizes": "192x192"

    },

    {

      "src": "img/logo512.png",

      "type": "image/png",

      "sizes": "512x512"

    }

  ],

  "display": "standalone",

  "start_url": "/"

}

Many Regards,
Khawaja

**Comment by khawaja74** [comment]
Hi Nickolay,
Any suggestions for claims based auth using this template. Any video or material help ful to learn and implement in .net core template

Regards
Khawaja
________________________________
