### ISSUE TITLE
Switch SendGrid with MailKit 

### ISSUE THREAD

**Issue by IliyanAng** [NikolayIT/ASP.NET-Core-Template#59]
Hey Niki! 
Before investing too much time in a PR, wanted to check whether this is something that will be considered improvement to the templates code base. 

Pros for MailKit: 
 - Open Source
 - MIT license
 - No limitations for reading/writing emails 
 - Dives deep in emails structure

Cons for MailKit: 
 - Requires a real instance of an email, from which to send/receive mails. 
 - If not careful with the git ignore, people can commit their **email username and password**s 
 - Slightly steeper learning curve from SendGrid

**Comment by NikolayIT** [comment]
Its a good suggestion but Send Grid is easier to use :)
