### ISSUE TITLE
Please enable multi tenants in this template 

### ISSUE THREAD

**Issue by khawaja74** [NikolayIT/ASP.NET-Core-Template#62]
Hi Nickolay this is Feature request, please add multi tenants in template this will enable students to be able to host for more than one client. Microsoft pushing everything multi tenants.

**Comment by ArsenioInojosa** [comment]
Hi, I added support for that.

It's been around for a while so I guess the team doesn't want to integrate it but you can use it.

Please look at the PR #63 

Sincerely, Arsenio.

**Comment by khawaja74** [comment]
I am already using this since your PR came in, thank you so much. Nick will merge it later

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by khawaja74** [comment]
well done
