### ISSUE TITLE
Pattern Exposing api to mobile apps

### ISSUE THREAD

**Issue by papyr** [NikolayIT/ASP.NET-Core-Template#68]
Hello I am looking for some guidance on mobile apps to work with your template structure

**Comment by khawaja74** [comment]
PWA(progressive-web-app) and it would be really good addition to your already amazing template.

Even making Presscenters.com as an installable app n the mobile devices. All it Needs is following in the template

  1.  dotnet add package WebEssentials.AspNetCore.PWA
  2.  two icons in /img folder "sizes": "192x192" "sizes": "512x512"
  3.  manifest.json in wwwroot
  4.  Add to the ConfigureServices(IServiceCollection services)
  5.  {
  6.        services.AddProgressiveWebApp();
  7.  }

details are here:

https://www.c-sharpcorner.com/article/progressive-web-app-pwa-in-asp-net-core/



Here is the manifest.json I used in the template



{

  "name": "Template",

  "short_name": "T",

  "description": "PWA",

  "icons": [

    {

      "src": "/img/logo192.png",

      "type": "image/png",

      "sizes": "192x192"

    },

    {

      "src": "img/logo512.png",

      "type": "image/png",

      "sizes": "512x512"

    }

  ],

  "display": "standalone",

  "start_url": "/"

}



Many Regards,

Khawaja

Sent from my iPhone

On Dec 6, 2020, at 9:04 AM, papyr <notifications@github.com> wrote:

﻿

Hello I am looking for some guidance on mobile apps to work with your template structure
